#!/bin/bash
# CGI test script in a second language (bash) — proves the CGI mechanism
# is interpreter-agnostic, not hardcoded to Python.

echo "Content-Type: text/html"
echo ""

body=""
if [ "$REQUEST_METHOD" = "POST" ] && [ -n "$CONTENT_LENGTH" ] && [ "$CONTENT_LENGTH" -gt 0 ]; then
    body=$(head -c "$CONTENT_LENGTH")
fi

cat << HTML
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Bash CGI — System Info</title>
<style>
  body{font-family:sans-serif;background:#0f0f1a;color:#e2e8f0;padding:2rem;}
  h1{color:#a3b0ff;margin-bottom:0.25rem;}
  .subtitle{color:#718096;margin-bottom:2rem;font-size:0.9rem;}
  h2{color:#7b8cde;margin:1.5rem 0 0.75rem;font-size:1.1rem;}
  table{width:100%;border-collapse:collapse;margin-bottom:1rem;font-size:0.85rem;}
  th{text-align:left;padding:0.5rem 0.75rem;background:#1a1a2e;color:#a0aec0;border-bottom:1px solid #2d3748;}
  td{padding:0.4rem 0.75rem;border-bottom:1px solid #1a1a2e;font-family:monospace;}
  td:first-child{color:#f6ad55;width:30%;}
  td:last-child{color:#68d391;word-break:break-all;}
  .body-box{background:#1a1a2e;border:1px solid #2d3748;border-radius:8px;padding:1rem;
            font-family:monospace;font-size:0.85rem;color:#68d391;white-space:pre-wrap;}
  a{color:#7b8cde;text-decoration:none;}
  .back-btn{display:inline-block;margin-bottom:1.5rem;padding:0.4rem 1rem;
            border:1px solid #7b8cde;border-radius:6px;}
</style>
</head>
<body>
<a href="/" class="back-btn">&#8592; Home</a>
<h1>Bash CGI — System Info</h1>
<p class="subtitle">Generated by /bin/bash, not Python — same server, second interpreter.</p>

<h2>Request</h2>
<table>
<tr><th>Variable</th><th>Value</th></tr>
<tr><td>REQUEST_METHOD</td><td>${REQUEST_METHOD}</td></tr>
<tr><td>QUERY_STRING</td><td>${QUERY_STRING}</td></tr>
<tr><td>SCRIPT_FILENAME</td><td>${SCRIPT_FILENAME}</td></tr>
<tr><td>SERVER_SOFTWARE</td><td>${SERVER_SOFTWARE}</td></tr>
<tr><td>SERVER_PROTOCOL</td><td>${SERVER_PROTOCOL}</td></tr>
</table>

<h2>Server host info</h2>
<table>
<tr><th>Field</th><th>Value</th></tr>
<tr><td>uname -a</td><td>$(uname -a)</td></tr>
<tr><td>uptime</td><td>$(uptime -p 2>/dev/null || uptime)</td></tr>
<tr><td>date</td><td>$(date)</td></tr>
<tr><td>pwd (cwd at exec)</td><td>$(pwd)</td></tr>
</table>
HTML

if [ "$REQUEST_METHOD" = "POST" ]; then
cat << HTML
<h2>Request Body</h2>
<div class="body-box">$([ -n "$body" ] && echo "$body" || echo "(empty body)")</div>
HTML
fi

cat << HTML
<h2>Try it</h2>
<form method="GET" action="/cgi-bin/sysinfo.sh" style="margin-top:0.5rem">
    <input type="text" name="msg" placeholder="Message"
           style="background:#1a1a2e;border:1px solid #2d3748;color:#e2e8f0;
                  padding:0.4rem 0.75rem;border-radius:6px;margin-right:0.5rem;">
    <button type="submit"
            style="background:#7b8cde;color:#fff;border:none;padding:0.4rem 1rem;
                   border-radius:6px;cursor:pointer;">Send GET</button>
</form>
</body>
</html>
HTML
