#!/usr/bin/env python3
# CGI test script - displays all environment variables and request info

import os
import sys

# Output CGI headers
print("Content-Type: text/html")
print("")

# Read body if POST
body = ""
method = os.environ.get("REQUEST_METHOD", "GET")
if method == "POST":
    content_length = int(os.environ.get("CONTENT_LENGTH", "0") or "0")
    if content_length > 0:
        body = sys.stdin.read(content_length)

# HTML output
print("""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CGI Environment Test</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body {
            font-family: 'Segoe UI', sans-serif;
            background: #0f0f1a;
            color: #e2e8f0;
            padding: 2rem;
        }
        h1 { color: #a3b0ff; margin-bottom: 0.25rem; }
        .subtitle { color: #718096; margin-bottom: 2rem; font-size: 0.9rem; }
        h2 { color: #7b8cde; margin: 1.5rem 0 0.75rem; font-size: 1.1rem; }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 1rem;
            font-size: 0.85rem;
        }
        th {
            text-align: left;
            padding: 0.5rem 0.75rem;
            background: #1a1a2e;
            color: #a0aec0;
            border-bottom: 1px solid #2d3748;
        }
        td {
            padding: 0.4rem 0.75rem;
            border-bottom: 1px solid #1a1a2e;
            font-family: monospace;
        }
        td:first-child { color: #f6ad55; width: 40%; }
        td:last-child  { color: #68d391; word-break: break-all; }
        tr:hover td { background: #1a1a2e; }
        .body-box {
            background: #1a1a2e;
            border: 1px solid #2d3748;
            border-radius: 8px;
            padding: 1rem;
            font-family: monospace;
            font-size: 0.85rem;
            color: #68d391;
            white-space: pre-wrap;
            word-break: break-all;
        }
        a {
            color: #7b8cde;
            text-decoration: none;
        }
        .back-btn {
            display: inline-block;
            margin-bottom: 1.5rem;
            padding: 0.4rem 1rem;
            border: 1px solid #7b8cde;
            border-radius: 6px;
            color: #7b8cde;
            font-size: 0.85rem;
        }
        .back-btn:hover { background: #7b8cde; color: #fff; }
    </style>
</head>
<body>
<a href="/" class="back-btn">&#8592; Home</a>
<h1>CGI Environment Test</h1>
<p class="subtitle">This page is generated by a Python CGI script. All environment variables are listed below.</p>
""")

# CGI Standard Variables
cgi_vars = [
    "REQUEST_METHOD", "QUERY_STRING", "CONTENT_TYPE", "CONTENT_LENGTH",
    "SCRIPT_NAME", "SCRIPT_FILENAME", "PATH_INFO", "PATH_TRANSLATED",
    "SERVER_NAME", "SERVER_PORT", "SERVER_PROTOCOL", "SERVER_SOFTWARE",
    "GATEWAY_INTERFACE", "REDIRECT_STATUS", "DOCUMENT_ROOT"
]

print("<h2>CGI Variables</h2>")
print("<table><tr><th>Variable</th><th>Value</th></tr>")
for var in cgi_vars:
    val = os.environ.get(var, "<em style='color:#718096'>not set</em>")
    print("<tr><td>{}</td><td>{}</td></tr>".format(var, val))
print("</table>")

# HTTP Headers
print("<h2>HTTP Headers</h2>")
print("<table><tr><th>Header</th><th>Value</th></tr>")
for key, val in sorted(os.environ.items()):
    if key.startswith("HTTP_"):
        header_name = key[5:].replace("_", "-").title()
        print("<tr><td>{}</td><td>{}</td></tr>".format(header_name, val))
print("</table>")

# All environment variables
print("<h2>All Environment Variables</h2>")
print("<table><tr><th>Variable</th><th>Value</th></tr>")
for key, val in sorted(os.environ.items()):
    print("<tr><td>{}</td><td>{}</td></tr>".format(key, val))
print("</table>")

# Query string parsed
qs = os.environ.get("QUERY_STRING", "")
if qs:
    print("<h2>Query String Parameters</h2>")
    print("<table><tr><th>Parameter</th><th>Value</th></tr>")
    for pair in qs.split("&"):
        if "=" in pair:
            k, v = pair.split("=", 1)
            print("<tr><td>{}</td><td>{}</td></tr>".format(k, v))
        elif pair:
            print("<tr><td>{}</td><td><em>no value</em></td></tr>".format(pair))
    print("</table>")

# Request body
if method == "POST":
    print("<h2>Request Body</h2>")
    print('<div class="body-box">')
    if body:
        print(body[:2000])
        if len(body) > 2000:
            print("\n... ({} bytes total, showing first 2000)".format(len(body)))
    else:
        print("(empty body)")
    print("</div>")

# Test form
print("""
<h2>Test GET with Query String</h2>
<form method="GET" action="/cgi-bin/test.py" style="margin-top:0.5rem">
    <input type="text" name="name" placeholder="Your name"
           style="background:#1a1a2e;border:1px solid #2d3748;color:#e2e8f0;
                  padding:0.4rem 0.75rem;border-radius:6px;margin-right:0.5rem;">
    <input type="text" name="msg" placeholder="Message"
           style="background:#1a1a2e;border:1px solid #2d3748;color:#e2e8f0;
                  padding:0.4rem 0.75rem;border-radius:6px;margin-right:0.5rem;">
    <button type="submit"
            style="background:#7b8cde;color:#fff;border:none;padding:0.4rem 1rem;
                   border-radius:6px;cursor:pointer;">Send GET</button>
</form>

<h2>Test POST</h2>
<form method="POST" action="/cgi-bin/test.py" style="margin-top:0.5rem">
    <textarea name="data" rows="4"
              style="background:#1a1a2e;border:1px solid #2d3748;color:#e2e8f0;
                     padding:0.4rem 0.75rem;border-radius:6px;width:100%;
                     margin-bottom:0.5rem;font-family:monospace;">Hello from POST!</textarea>
    <button type="submit"
            style="background:#68d391;color:#0f0f1a;border:none;padding:0.4rem 1rem;
                   border-radius:6px;cursor:pointer;font-weight:bold;">Send POST</button>
</form>
""")

print("</body></html>")
